version: '3'
services:
  postgres:
    container_name: 'jnotsj-pg'
    image: "postgres:alpine"
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'test2'
      POSTGRES_DB: 'nots'
  kafka:
    container_name: 'jnotsj-kafka'
    image: "spotify/kafka"
    ports:
      - '9092:9092'
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: '9092'
      TOPICS: 'users'