version: '3'
services:
  be:
    container_name: 'jnotsj-be'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nots
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - '9090:9090'
    volumes:
      - ./build:/tmp
  postgres:
    container_name: 'jnotsj-pg'
    image: "postgres:alpine"
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'test2'
      POSTGRES_DB: 'nots'
  kafka:
    container_name: 'jnotsj-kafka'
    image: "spotify/kafka"
    expose:
      - 9092
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: '9092'
      TOPICS: 'users'