version: '3'
services:
  postgres :
    container_name: 'jnotsj-pg'
    image: "postgres:11-alpine"
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'test2'
      POSTGRES_DB: 'nots'
      POSTGRES_PASSWORD: 'test2'
  zookeeper:
    container_name: 'jnotsj-zookeeper'
    image: 'zookeeper:latest'
    ports:
      - '2181:2181'
  kafka:
    container_name: 'jnotsj-kafka'
    image: "wurstmeister/kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'mail:1:1'